In [1]:
import numpy as np

In [4]:
arr=np.arange(10,75,2,dtype=float)

In [6]:
arr.dtype

dtype('float64')

In [7]:
arr

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34.,
       36., 38., 40., 42., 44., 46., 48., 50., 52., 54., 56., 58., 60.,
       62., 64., 66., 68., 70., 72., 74.])

In [8]:
arr=np.linspace(0,1,11)

In [9]:
arr

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [10]:
a1=np.array([[1,2,3],[4,5,6]])

In [11]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a1.sum()

21

In [15]:
np.sum(a1,axis=0)

array([5, 7, 9])

In [16]:
np.sum(a1,axis=1)

array([ 6, 15])

In [17]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])

In [18]:
#4+10+18=32    dot product

In [19]:
np.dot(a1,a2)

32

In [20]:
#2x2 matrix and find dot product

In [21]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])

In [22]:
np.dot(a1,a2)

array([[19, 22],
       [43, 50]])

In [23]:
a1

array([[1, 2],
       [3, 4]])

In [24]:
a2

array([[5, 6],
       [7, 8]])

In [25]:
import pandas as pd

In [26]:
data=np.array([12,34,56,78])

In [27]:
s1=pd.Series(data)

In [28]:
print(s1)

0    12
1    34
2    56
3    78
dtype: int32


In [29]:
s1=pd.Series(data,index=['a','b','c','d'])

In [30]:
s1

a    12
b    34
c    56
d    78
dtype: int32

In [31]:
type(s1)

pandas.core.series.Series

In [32]:
s1.shape

(4,)

In [33]:
s1.values

array([12, 34, 56, 78])

In [34]:
s1.ndim

1

In [35]:
s1[1:3]

b    34
c    56
dtype: int32

In [38]:
s1[0:2].values

array([12, 34])

In [39]:
s1[0:2]

a    12
b    34
dtype: int32

In [40]:
s1['a':'b']

a    12
b    34
dtype: int32

In [41]:
#create array with 5 elements 21.....,convert to pandas series and add index

In [42]:
np.array([21,22,23,24,25])

array([21, 22, 23, 24, 25])

In [43]:
data=np.array([21,22,23,24,25])

In [44]:
s1=pd.Series(data,index=['A','B','C','D','E'])

In [45]:
s1

A    21
B    22
C    23
D    24
E    25
dtype: int32

In [46]:
#DataFrames

In [51]:
df=pd.DataFrame([[1,2,3],[4,5,6]],index=['r1','r2'])

In [52]:
df

0  1  2
r1  1  2  3
r2  4  5  6

In [53]:
df=pd.DataFrame([[1,2,3],[4,5,6]],index=['r1','r2'],columns=['c1','c2','c3'])

In [54]:
df

c1  c2  c3
r1   1   2   3
r2   4   5   6

In [55]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=['r1','r2','r3'],columns=['c1','c2','c3'])

In [56]:
df

c1  c2  c3
r1   1   2   3
r2   4   5   6
r3   7   8   9

In [57]:
df.shape

(3, 3)

In [58]:
d={'name':['ishan','sanjay'], 'age':[20,51],'marks':[99,99]}

In [59]:
df=pd.DataFrame(d)

In [60]:
df

name  age  marks
0   ishan   20     99
1  sanjay   51     99

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    2 non-null      object
 1   age     2 non-null      int64 
 2   marks   2 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 176.0+ bytes


In [62]:
df.describe()

age  marks
count   2.00000    2.0
mean   35.50000   99.0
std    21.92031    0.0
min    20.00000   99.0
25%    27.75000   99.0
50%    35.50000   99.0
75%    43.25000   99.0
max    51.00000   99.0

In [63]:
#https://drive.google.com/drive/folders/18PJHkeCvIgyoKg2LFJlCVFG10QD9edds?usp=sharing

In [66]:
df=pd.read_csv('student_data.csv')

In [67]:
df

roll     name class  marks   age
0     1     anil    TE  56.77  22.0
1     2     amit    TE  59.77  21.0
2     3   aniket    BE    NaN  19.0
3     4  ajinkya    TE  69.66  20.0
4     5     asha    TE  63.28  20.0
5     6   ayesha    BE  49.55   NaN
6     7     amar    BE  65.34  19.0
7     8    amita    BE  68.33  23.0
8     9     amol    TE  56.75  20.0
9    10    anmol    BE  78.66  21.0